version: "3.8"

services:
  web:
    image: ${IMAGE}         # Jenkins will inject IMAGE=flask-shopping-list:<buildTag>
    ports:
      - "5002:5000"         # exposed on http://<jenkins-host>:5002
    env_file:
      - .env.staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
