# (optional) remove 'version:' line to silence the warning
services:
  web:
    image: ${IMAGE}
    ports:
      - "5002:5000"
    env_file:
      - ./staging.env   # <— from inside the deploy folder
    environment:
      CI: "true"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:5000/health'); sys.exit(0)"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: unless-stopped
