version: "3.9"
services:
  web:
    image: ${IMAGE}              # set by the Jenkins stage
    ports:
      - "5002:5000"
    env_file:
      - ../staging.env           # <— add this
    environment:
      CI: "true"                 # keep only extras here; don't duplicate SECRET_KEY/FLASK_ENV
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: unless-stopped
