services:
  web:
    image: ${IMAGE}              # Jenkins exports IMAGE before running compose
    ports:
      - "5002:5000"              # host:container (staging on 5002)
    env_file:
      - ./staging.env            # read KEY=VALUE pairs from this file
    environment:
      CI: "true"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: unless-stopped
